spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/flutter-blog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      fail-on-emptybeans: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
